name: Decompile APK to Java

on:
  workflow_dispatch:
    inputs:
      apk_path:
        description: 'Path to APK file in repo'
        required: true
        default: 'app.apk'

jobs:
  decompile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Java (OpenJDK 11)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download dex2jar
        run: |
          wget https://github.com/pxb1988/dex2jar/releases/download/v2.1/dex2jar-2.1.zip
          unzip dex2jar-2.1.zip
          chmod +x dex2jar-2.1/d2j-dex2jar.sh

      - name: Convert dex to jar
        run: |
          ./dex2jar-2.1/d2j-dex2jar.sh ${{ github.workspace }}/${{ github.event.inputs.apk_path }} -o output.jar

      - name: Download CFR decompiler
        run: |
          wget http://www.benf.org/other/cfr/cfr-0.152.jar -O cfr.jar

      - name: Decompile jar to Java
        run: |
          java -jar cfr.jar output.jar --outputdir decompiled_source

      - name: Upload Decompiled Source as artifact
        uses: actions/upload-artifact@v3
        with:
          name: decompiled-source
          path: decompiled_source
