name: Sync main to all branches

on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get all branches
        run: |
          # Get list of all remote branches except main
          git fetch --all
          branches=$(git branch -r | grep -v 'main' | sed 's/origin\///')
          echo "Branches to sync: $branches"
          echo "$branches" > branches.txt

      - name: Sync branches
        run: |
          # Loop through each branch and sync with main
          while read branch; do
            echo "Syncing branch $branch"
            git checkout $branch
            git merge origin/main -X theirs --no-edit --allow-unrelated-histories || true
            git push origin $branch
          done < branches.txt
