name: Sync from upstream (excluding upstream workflows)

on:
#  schedule:
#    - cron: '0 20 * * 1'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/anilbeesetti/nextplayer.git
          git fetch upstream

      - name: Enable sparse checkout (exclude upstream workflows)
        run: |
          git sparse-checkout init --no-cone
          echo "/*" > .git/info/sparse-checkout
          echo "!/.github/workflows/*" >> .git/info/sparse-checkout
          git sparse-checkout reapply

      - name: Merge from upstream (excluding workflows)
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "Nothing to merge"

      - name: Push to origin/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin main
