name: Sync branch main to all

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull from main
        run: |
          for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/ | grep -v '^main$'); do
            echo "Syncing main to $branch"
            git checkout $branch
            git merge main -X theirs --no-edit --allow-unrelated-histories || true
            git push origin $branch
          done
